### ISSUE TITLE
iGEN-NET: ValueError: No variables to optimize.

### ISSUE THREAD

**Issue by curehabit** [Salingo/PGDNN#2]
When i trained iGEN-NET, it raised a ValueError:

> Traceback (most recent call last):
  File "train.py", line 91, in <module>
    optimizer_ts = tf.train.AdamOptimizer(learning_rate=LEARNING_RATE).minimize(iGEN.ts_loss, var_list=para_ts)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 343, in minimize
    grad_loss=grad_loss)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 408, in compute_gradients
    raise ValueError("No variables to optimize.")
ValueError: No variables to optimize.

I try to print para_ts and para_rec, but both of them are empty .

**Comment by Salingo** [comment]
Thanks for finding a bug, I already fixed it, welcome to try again.
